/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.android.builder;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.SwingWorker;
import javax.swing.filechooser.FileFilter;
import javax.swing.text.DefaultEditorKit;

/**
 *
 * @author zhangfei
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        setLocationRelativeTo(null);

        JPopupMenu popup = new JPopupMenu();
        JMenuItem item = new JMenuItem(new DefaultEditorKit.CutAction());
        item.setText("剪切");
        popup.add(item);
        item = new JMenuItem(new DefaultEditorKit.CopyAction());
        item.setText("复制");
        popup.add(item);
        item = new JMenuItem(new DefaultEditorKit.PasteAction());
        item.setText("粘贴");
        popup.add(item);

        jTextArea_channels.setComponentPopupMenu(popup);
        jTextField_apkPath.setComponentPopupMenu(popup);
        jTextField_outputPath.setComponentPopupMenu(popup);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_default = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_apkPath = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_outputPath = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_channels = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jProgressBar_build = new javax.swing.JProgressBar();
        jButton_chooseApk = new javax.swing.JButton();
        jButton_chooseOutputPath = new javax.swing.JButton();
        jButton_buildApks = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Android多渠道批量打包");
        setBackground(java.awt.Color.white);
        setResizable(false);

        jPanel_default.setBackground(java.awt.Color.white);
        jPanel_default.setForeground(java.awt.SystemColor.activeCaptionBorder);

        jLabel1.setText("Apk原文件:");

        jLabel2.setText("输出路径:");

        jLabel4.setText("渠道号:");

        jTextArea_channels.setColumns(1);
        jTextArea_channels.setRows(5);
        jScrollPane1.setViewportView(jTextArea_channels);

        jLabel5.setText("生成进度:");

        jButton_chooseApk.setText("选择");
        jButton_chooseApk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_chooseApkMouseClicked(evt);
            }
        });

        jButton_chooseOutputPath.setText("选择");
        jButton_chooseOutputPath.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_chooseOutputPathMouseClicked(evt);
            }
        });

        jButton_buildApks.setText("开始");
        jButton_buildApks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_buildApksMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_defaultLayout = new javax.swing.GroupLayout(jPanel_default);
        jPanel_default.setLayout(jPanel_defaultLayout);
        jPanel_defaultLayout.setHorizontalGroup(
            jPanel_defaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_defaultLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel_defaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_defaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_apkPath)
                    .addComponent(jTextField_outputPath)
                    .addComponent(jScrollPane1)
                    .addComponent(jProgressBar_build, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_defaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_chooseApk)
                    .addComponent(jButton_chooseOutputPath)
                    .addComponent(jButton_buildApks))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel_defaultLayout.setVerticalGroup(
            jPanel_defaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_defaultLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel_defaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_apkPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_chooseApk)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_defaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_outputPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_chooseOutputPath))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_defaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jButton_buildApks)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_defaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jProgressBar_build, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_default, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_default, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_chooseApkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_chooseApkMouseClicked
        JFileChooser jfc = new JFileChooser();
        jfc.setDialogTitle("请选择APK原文件");
        jfc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        jfc.setFileFilter(new FileFilter() {
            @Override
            public boolean accept(File f) {
                return f.getName().endsWith(".apk");
            }

            @Override
            public String getDescription() {
                return ".apk";
            }
        });

        int result = jfc.showOpenDialog(this);

        if (JFileChooser.APPROVE_OPTION == result) {
            File file = jfc.getSelectedFile();
            jTextField_apkPath.setText(file.getAbsolutePath());
        }
    }//GEN-LAST:event_jButton_chooseApkMouseClicked

    private void jButton_chooseOutputPathMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_chooseOutputPathMouseClicked
        JFileChooser jfc = new JFileChooser();
        jfc.setDialogTitle("请选择输出路径");
        jfc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int result = jfc.showOpenDialog(this);

        if (JFileChooser.APPROVE_OPTION == result) {
            File selectedFile = jfc.getSelectedFile();
            File[] files = jfc.getSelectedFile().listFiles();
            for (File file : files) {
                file.delete();
            }
            jTextField_outputPath.setText(selectedFile.getAbsolutePath());
        }
    }//GEN-LAST:event_jButton_chooseOutputPathMouseClicked

    private void jButton_buildApksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_buildApksMouseClicked
        jButton_buildApks.setEnabled(false);
        
        // reset progress
        jProgressBar_build.setValue(0);

        String srcFilePath = jTextField_apkPath.getText().trim();
        String outputPath = jTextField_outputPath.getText().trim();
        String channelsText = jTextArea_channels.getText().trim();

        // validate params
        if (srcFilePath == null || srcFilePath.length() <= 0) {
            JOptionPane.showMessageDialog(jPanel_default, "请先选择APK源文件", "警告信息", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (outputPath == null || outputPath.length() <= 0) {
            JOptionPane.showMessageDialog(jPanel_default, "请先选择渠道包输出路径", "警告信息", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (channelsText == null || channelsText.length() <= 0) {
            JOptionPane.showMessageDialog(jPanel_default, "请先填好批量渠道号", "警告信息", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String[] channels = channelsText.split("\n");

        SwingWorker swingWorker = new SwingWorker<List<Integer>, Integer>() {

            @Override
            protected List<Integer> doInBackground() throws Exception {
                List<Integer> list = new ArrayList<>();
                
                try {
                    Builder.build(new File(srcFilePath), outputPath, channels, new ProgressListener() {
                        @Override
                        public void onProgress(String channel, int percentage) {
                            list.clear();
                            list.add(percentage);
                            publish(percentage);
                        }
                    });
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(jPanel_default, "错误原因:" + ex.getMessage(), "打包失败", JOptionPane.ERROR_MESSAGE);
                    System.exit(0);
                }
                return list;
            }

            @Override
            protected void process(List<Integer> chunks) {
                int percentage = chunks.get(0);
                jProgressBar_build.setValue(percentage);
            }

            @Override
            protected void done() {
                jProgressBar_build.setValue(100);
                jButton_buildApks.setEnabled(true);
                
                Object[] options = {"确定", "取消"};
                int response = JOptionPane.showOptionDialog(jPanel_default,
                        "是否打开文件夹?",
                        "打包已完成",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE,
                        null, options, options[0]);

                if (response == 0) {
                    try {
                        String outputDir = jTextField_outputPath.getText().trim();
                        if (outputDir == null || outputDir.length() == 0) {
                            JOptionPane.showMessageDialog(null, "输出路径为空", "警告信息", JOptionPane.WARNING_MESSAGE);
                            return;
                        }
                        Desktop.getDesktop().open(new java.io.File(outputDir));
                    } catch (IOException ex) {
                        Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        };
        swingWorker.execute();
    }//GEN-LAST:event_jButton_buildApksMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainJFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_buildApks;
    private javax.swing.JButton jButton_chooseApk;
    private javax.swing.JButton jButton_chooseOutputPath;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel_default;
    private javax.swing.JProgressBar jProgressBar_build;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_channels;
    private javax.swing.JTextField jTextField_apkPath;
    private javax.swing.JTextField jTextField_outputPath;
    // End of variables declaration//GEN-END:variables
}
